apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
    name: jx-production
    team: 'jx'
  name: jx-production
spec: {}
status: {}
