apiVersion: v1
appVersion: 1.2.47
description: A Helm chart for the resources for JX Boot
home: https://github.com/jenkins-x-charts/jxboot-helmfile-resources
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
name: jxboot-helmfile-resources
sources:
- https://github.com/jenkins-x-charts/jxboot-helmfile-resources.git
version: 1.2.47
